apiVersion: v1
kind: Service
metadata:
  name: devrunner-prod-batch
  namespace: devrunner-prod-batch
spec:
  selector:
    app: devrunner-prod-batch
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
